version: '3.4'

services:
  nginx:
    container_name: web-app-nginx
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
      target: prod
    restart: always
    volumes:
      - ./public:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - php

  php:
    container_name: web-app-php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      target: prod
      args:
        UID: $U_ID
    restart: always
    volumes:
      - ./:/var/app