version: '3.4'

services:
  nginx:
    container_name: web-app-nginx
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
      target: basic
    volumes:
      - ./public:/var/www/html
    ports:
      - "8081:80"
    depends_on:
      - php

###> symfony/mailer ###
  mailer:
    image: schickling/mailcatcher
    ports: [ "1025", "1080" ]
###< symfony/mailer ###

  php:
    container_name: web-app-php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      target: dev
      args:
        UID: $U_ID
    volumes:
      - ./:/var/app
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    container_name: web-app-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: guest
      POSTGRES_PASSWORD: guest
      POSTGRES_DB: web-app
    volumes:
      - web_app_data:/var/lib/postgresql/data

volumes:
  web_app_data:
